[package]
name = "TroveMigrationTool"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.52"
platform-dirs = "0.3.0"